### ISSUE TITLE
Differenc between Districts and Cities

### ISSUE THREAD

**Issue by Charly-de** [lavolp3/MMM-COVID19-Inc#2]
Hello,
 I’ve been using your Covid19 module since last week.  First class work!

 But now I noticed something:
 If I display the values ​​for "Nürnberg" and "Nürnberger Land" in the bar view of the incidences, 
only the values ​​for the district of "Nürnberger Land" are displayed for both, not for the city of "Nürnberg".
 The city of "Nürnberg" does not belong to the district of "Nürnberger Land".

 The same applies to the district of "Amberg-Sulzbach" and the city of "Amberg".
 The cities are listed separately at api.corona-zahlen.org/districts.

 Is it not possible to compare town and district or am I getting something wrong?

 Otherwise everything works fine.

 Thank you for the module.

Greetings

**Comment by lavolp3** [comment]
I have created a workaround for this. 
I found no easy way of sorting the issue for now.
You can now use the district codes from the API in the districts array as well as names.
For the Nürnberg ones use:  [09564, 09574].
It should work then. Please confirm

**Comment by Charly-de** [comment]
I can confirm that the workaround works!
Good work thx
